[package]
name = "beautiful_qrcode_generator_beemly"
version = "0.1.0"
authors = ["Lancelot OWCZARCZAK <lowczarc@student.42.fr>"]
edition = "2018"

[dependencies]
qrcode-generator = "1.0.4"
image = "0.21.1"
